# Generated by Django 4.1.7 on 2023-04-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=12)),
            ],
        ),
    ]
