# Generated by Django 4.1.7 on 2023-04-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='proprietario',
            options={'verbose_name': 'proprietario', 'verbose_name_plural': 'proprietarios'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='sobrenome',
        ),
    ]
