# Generated by Django 4.1.7 on 2023-04-23 00:11

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto_perfil',
            field=stdimage.models.StdImageField(default='fotos_perfil/default.png', force_min_size=False, upload_to=core.models.get_file_path_profile, variations={'thumbnail': (60, 60, True)}, verbose_name='foto_perfil'),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='foto_perfil',
            field=stdimage.models.StdImageField(default='fotos_perfil/default.png', force_min_size=False, upload_to=core.models.get_file_path_profile, variations={'thumbnail': (60, 60, True)}, verbose_name='foto_perfil'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='salao_image',
            field=stdimage.models.StdImageField(default='fotos_salao/default.jpg', force_min_size=False, upload_to=core.models.get_file_path_salon, variations={'thumbnail': (700, 200, True)}, verbose_name='salao_image'),
        ),
    ]
