# Generated by Django 4.1.7 on 2023-04-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='bairro',
            field=models.CharField(default='Sem local', max_length=30),
        ),
        migrations.AddField(
            model_name='salon',
            name='cidade',
            field=models.CharField(default='Sem local', max_length=30),
        ),
        migrations.AddField(
            model_name='salon',
            name='numero',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salon',
            name='pais',
            field=models.CharField(default='Sem local', max_length=30),
        ),
        migrations.AddField(
            model_name='salon',
            name='rua',
            field=models.CharField(default='Sem local', max_length=100),
        ),
    ]
