# Generated by Django 4.1.7 on 2023-05-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_salon_bairro_salon_cidade_salon_numero_salon_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
