# Generated by Django 4.1.7 on 2023-05-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicos_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='Cidade', max_length=30),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(default='uf', max_length=2),
        ),
    ]
