# Generated by Django 4.1.7 on 2023-05-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_salon_salao_image_salon_imagem_salao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='servicos',
            name='duracao_maxima_homem',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='duracao_maxima_mulher',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
