# Generated by Django 4.1.7 on 2023-05-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_sexo_servicos_duracao_maxima_homem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='duracao_maxima_homem',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='duracao_maxima_mulher',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(default='', max_length=20)),
                ('total_pagar', models.FloatField()),
                ('dia_selecionado', models.CharField(default='', max_length=30)),
                ('horario_selecionado', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario')),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salon')),
                ('servico', models.ManyToManyField(to='core.servicos')),
            ],
        ),
    ]
