# Generated by Django 4.1.7 on 2023-06-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_servicos_duracao_maxima_homem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheAgendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(default='', max_length=20)),
                ('total_pagar', models.FloatField()),
                ('dia_selecionado', models.CharField(default='', max_length=30)),
                ('horario_selecionado', models.TimeField()),
                ('data_concluido', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario')),
                ('salao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.salon')),
                ('servico', models.ManyToManyField(to='core.servicos')),
            ],
        ),
    ]
